%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB (R2024a) and Database Toolbox Version 24.1 on 02-Apr-2024 13:41:19

%% Make connection to database
conn = postgresql('WRDS','givani30','_6S-,NjBcTQ*dbG');

%Set query to execute on the database
query = ['SELECT a.*, b.ret, b.date ' ...
    'FROM crsp.dsp500list AS a ' ...
    'INNER JOIN crsp.dsf AS b ON a.permno = b.permno ' ...
    'WHERE b.date >= ''2000-01-01'' AND b.date <= a.ending ' ...
    '  AND a.start >= ''2000-01-01'' ' ...
    'ORDER BY b.date'];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query